dist: xenial
language: php
services:
  - docker
php:
- 7.2
- 7.3
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
install:
- nvm install 12
- npm install
- composer install
- npm run build
script:
- npm run test
